#!/bin/bash

# Tag a successful build as latest without rebuilding
echo "Tagging image ${IMAGE_NAME} as 'latest'..."
docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest

echo "Tagging image ${IMAGE_NAME} as '18.04'..."
docker tag $IMAGE_NAME $DOCKER_REPO:18.04
docker push $DOCKER_REPO:18.04
